# request
string human_joint_dict
float32[] camera_position
float32[] camera_orientation
float32[] robot_position_world
float32[] robot_orientation_world

---
# response
float32[] tablet_position_robot_frame
float32[] tablet_orientation_robot_frame
float32[] robot_base_pose_xya
string robot_ik_solution_dict