# request
string human_joint_dict_robot_frame

---
# response
bool success
geometry_msgs/PoseStamped tablet_pose_robot_frame
# geometry_msgs/PointStamped robot_base_pose
string[] robot_ik_joint_names
float32[] robot_ik_joint_positions
float32 plan_time_s
